[package]
name = "bevy-bowling"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
bevy_editor_pls = "0.4.0"
bevy_iced = "0.3.0"
bevy_rapier3d = { version = "0.21.0", features = ["simd-stable", "parallel"] }
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3
